pull_request_rules:
- name: ping author on conflicts and add 'needs-rebase' label
  conditions:
      - conflict
      - -closed
  actions:
    label:
      add:
        - needs-rebase
    comment:
      message: >
       This pull request has merge conflicts that must be resolved before it
       can be merged. @{{author}} please rebase it.
       https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

- name: remove 'needs-rebase' label when conflict is resolved
  conditions:
      - -conflict
      - -closed
  actions:
    label:
      remove:
        - needs-rebase

- name: auto-merge on stable release branches
  conditions:
      - base~=^release-[0-9]+\.[0-9]+\.x$
      - check-success=ci-status
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - -conflict
      - -draft
      - -closed
  actions:
    merge:
      method: merge

- name: auto-merge dependabot github-deps PRs
  conditions:
      - author=dependabot[bot]
      - title~=^chore\(github-deps\)
      - check-success=ci-status
      - -conflict
      - -draft
      - -closed
  actions:
    merge:
      method: merge
